cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add/', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')), 
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('backoffice/', include('backoffice.urls', namespace='backoffice'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    image = models.ImageField(upload_to='media/', default='static/img/flags.png')
    name = models.CharField(max_length=50, null=False, blank=False)
    slug = models.SlugField(unique=True, max_length=100, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_path(self):
        return reverse('store:product_list') + f'?category={self.id}'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField(unique_for_date='created')
    description = models.TextField(null=False, blank=False)
    price = models.FloatField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/products/%Y/%m/%d/', blank=True)
    availibility = models.BooleanField(null=False, default=True)

    class Meta:
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_details', kwargs={'slug': self.slug})


class Carusel(models.Model):
    image = models.ImageField(upload_to='media/carusel/%Y/%m/%d/', blank=True)
    name = models.SlugField(unique=True, max_length=100, db_index=True)

store/views.py
from django.shortcuts import render
from django.views import generic
from store.models import Product, Category,Carusel
from django_filters.views import FilterView
from store.filters import ProductFilter
from cart.forms import CartForm
from django.db.models import Count
import random
# Create your views here.





class ProductList(FilterView):
    model = Product
    queryset = Product.objects.all()
    paginate_by = 6
    filterset_class = ProductFilter
    context_object_name = 'products'
    template_name = 'store/product_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'category_slug' in self.kwargs:
            qs = qs.filter(category__slug=self.kwargs['category_slug'])
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Users']=Product.objects.all().order_by('?')[:8]
        context['Categorya']=Category.objects.all()
        return context



class ProdcutDetails(generic.DetailView):
    model = Product
    template_name = 'store/product_details.html'
    context_object_name = 'product'

    def get_queryset(self):
        product = super().get_queryset()
        return product.select_related('category').annotate(
            total_purchases=Count('ordered'))


class CategoriesList(generic.ListView):
    template_name = 'store/categories_list.html'
    context_object_name = 'categories'
    queryset = Category.objects.all().annotate(num_products=Count('products'))

store/templates/store/categories_list.html
{% extends 'index.html' %} {% block title %} Categories {% endblock title %}
{% block content %}
<div class="row my-3">
  {% for c in categories %}
  <div class="col-lg-3 col-md-6 col-12 my-2 px-sm-2">
    <div class="card text-center">
      <div class="card-body">
        <h3 class="font-weight-light">
          <img class="card-img-top" src="{{ c.image.url }}" alt="Card image cap">
          <a href="{{ c.get_absolute_path }}">{{c.name}}</a>
        </h3>
      </div>
      <div class="card-footer">
        {{c.num_products}} Tovar{{c.num_products|pluralize}}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

store/templates/store/product_details.html
{% extends 'index.html'%} {% load thumbnail%} {% load store_tags%} {% block title %}
{{product.name}} {% endblock title %} {% block content%}
<nav>
  <ol class="breadcrumb mt-2">
    <li class="breadcrumb-item">
      <a href="{{product.category.get_absolute_url}}">{{product.category}}</a>
    </li>
    <li class="breadcrumb-item active">{{product.name}}</li>
  </ol>
</nav>
<div class="row mt-2 mb-4">
  <div class="col-lg-4 col-md-6 col-12">
    <img
      src="{% thumbnail product.image 500x0 %}"
      alt="{{product.name}}"
      class="img-fluid mx-auto d-block"
    />
  </div>
  <div class="col-lg-8 col-md-6 col-12">
    <h2 class="mt-md-0 mt-2">{{product.name}}</h2>
    <h3 class="font-weight-light">UZS {{product.price}} faqat</h3>
    <h4>
      {% if product.availibility %}
      <span class="badge badge-success">Sotuvda</span>
      {% else %}
      <span class="badge badge-danger">Sotuvda emas</span>
      {% endif %}
    </h4>
    <p>{{product.description}}</p>
    <p>
      Bought by <b>{{product.total_purchases}}</b>
      customer{{product.total_purchases|pluralize}}.
    </p>
    {% if user.is_authenticated %}
    {% if product.id in cart.keys %}
    <form action="{% url 'cart:add' %}" method="POST" style="max-width: 400px">
      {% csrf_token %}
      <input type="hidden" name="product_id" value="{{product.id}}">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Soni</span>
        </div>
        <input
          type="number"
          min="1"
          name="quantity"
          value="{{cart|getattr:product.id}}"
          required="required"
          class="form-control"
        />
        <div class="input-group-append btn-group">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-cart-plus fa-lg mr-2"></i> Yangilash
          </button>
          <a href="{% url 'cart:remove' product.id %}" class="btn btn-danger">
            <i class="fa fa-times fa-lg mr-2"></i> O'chirish
          </a>
        </div>
      </div>
    </form>
    {% elif product.availibility %}
    <form method="POST" action="{% url 'cart:add' %}">
      {% csrf_token %}
      <input type="hidden" name="quantity" value="1" />
      <input type="hidden" name="product_id" value="{{product.id}}" />
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-cart-plus fa-lg mr-2"></i> Savatchaga qo'shish
      </button>
    </form>
    {% else %}
    <button class="btn btn-primary" disabled>
      <i class="fa fa-cart-plus fa-lg mr-2"></i> Savatchaga qo'shish'
    </button>
    {% endif %}
    {% else %}
    <a href="{% url 'login' %}" class="btn btn-primary" disabled>
      <i class="fa fa-sign-in fa-lg mr-2"></i> Savatchaga qo'shish uchun ro'yxatdan o'ting yoki ro'yxatdan o'ting
    </a>
    {% endif %}
  </div>
</div>
{% get_similar product.id product.price product.category %} 
{% endblock content%}

store/templates/store/product_list.html
{% extends 'index.html' %} {% load crispy_forms_tags %} {% load thumbnail %}
{% block title %}Store{% endblock title %}
{% block content %}
<style>
.filter-box{
  display:flex;

}
.filter-box .category-box{
  margin-right:30px;
  display:flex;
}


.category-i a{
  padding: 5px 10px;
  border: 2px solid #6D0069;
  border-radius: 6px; 
  color: #6D0069;
  font-weight: 600;
  transition: .3s;
}

.category-i a:hover{
background: #6D0069;
text-decoration:none;
color: white;
}
.price-form{
  display:flex;


}
.price-form button {
  margin-left: 10px;
  height: max-content;
  padding: 6px 12px;
  color: white;
  background: #6D0069;
  border: 2px solid #6D0069;
 transition: .3s;
}
.price-form button:hover{
  background: transparent;
  color: #6D0069;
  border: 2px solid #6D0069;
}

.price-form .textinput:focus{
  color: #6D0069;
   border-color: #6D0069;
    outline: 0;
    box-shadow: 0 0 0 0.2rem #6D0069;
}
.price-form .textinput{
  color: #6D0069;
   border-color: #6D0069;
    outline: 0;
   
}
#id_category{
  margin-right:30px;
  display:flex;
  padding: 5px 10px;
  margin-right:25px;
  border: 2px solid #6D0069;
  border-radius: 6px; 
  color: #6D0069;
  font-weight: 600;
  transition: .3s;
}
#div_id_category{
  width:400px;
  margin-right:10px
}
#id_category:hover{
background: #6D0069;
text-decoration:none;
color: white;
}
.card-title a:hover{
  color: #6D0069;
  text-decoration:none;
}
.card-title a{
  color:#6D0069;
}

</style>

<div id="carousel-example-2" class="carousel slide" data-ride="carousel">

  <ol class="carousel-indicators">
    <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-2" data-slide-to="1"></li>
    <li data-target="#carousel-example-2" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="view hm-white-slight">
        <img class="d-block w-100" src="https://i.ytimg.com/vi/BditV3ei2L4/maxresdefault.jpg" alt="First slide">
        <div class="mask"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive" style="color:#6D0069">First title</h3>
        <p style="color:#6D0069">First text</p>
      </div>
    </div>
    <div class="carousel-item">

      <div class="view hm-white-slight">
        <img class="d-block w-100" src="https://www.thecosmeticboxes.com/wp-content/uploads/2018/03/perfume-boxes5.jpg" alt="Second slide">
        <div class="mask"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive" style="color:#6D0069">Second title</h3>
        <p style="color:#6D0069">Second text</p>
      </div>
    </div>
    <div class="carousel-item">

      <div class="view hm-white-slight">
        <img class="d-block w-100" src="https://pro2-bar-s3-cdn-cf.myportfolio.com/efb920ee-2935-4c2d-8b89-74c0283625cb/803e753e-da81-4a06-8346-23fe0de05d30_rw_1920.jpg?h=977fbad162d15359686431acfc6bb9a9" alt="Third slide">
        <div class="mask"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive" style="color:#6D0069">Third title</h3>
        <p style="color:#6D0069">Third text</p>
      </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only" style="color:#6D0069">Ortga</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only" style="color:#6D0069">Keyingisi</span>
  </a>
  <!--/.Controls-->
</div>


</div>
</div>
</nav>

<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel" style="border:none">
  <center>
    <h1 class="font-weight-light" style="font-family: " Times New Roman", color:#6D0069">Bizning tovarlar</h1>
  </center>
  <!--Indicators-->
  <div class="carousel-inner" role="listbox" style="border:none">
    {% for p in  Users %}
    <!--First slide-->
    {% if forloop.counter0|divisibleby:4 %}
    <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" style="border:none"> {% endif %}

      <div class="col-md-3" style="float:left" style="border:none">
        <div class="card mb-4" style="width:300px; height:300px; justify-content:center; display:flex; border:none">
          <img class="w3-round" src="{{p.image.url}}" alt="Cardimg">
        </div>
      </div>
      {% if forloop.counter|divisibleby:4 or forloop.last %}
    </div>{% endif %}
    {% endfor%}
    <!--/.First slide-->
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% comment %} <div class="filter-box align-items-center"> {% endcomment %}
    {% comment %} <div class="category-box">
    {% for i in Categorya%}


        <div class="category-i form-check"><a href="{{ c.get_absolute_path }}" >{{ i.name}}</a></div>
      

    {% endfor%}
    </div> {% endcomment %}


<div class="r t-rec t-rec_pt_15 t-rec_pb_135">
<center>
  <image src="/static/image/logohappy2.png" style="width:250px; heght:20px; display:flex"></center>
  <br>
  <h2 class="font-weight-light mb-2" style="text-align:center; color:#6D0069">Tovarlar</h2>
  <div class="row">
<div class="col-sm-10">
    <form class="form-group price-form align-items-end" style="width:350px">
      {{filter.form|crispy}}
      <button class="btn btn-info btn-sm mb-3" type="submit">
        Filter
      </button>
    </form>
</div>
</div>
</div>

  <div class="row">
    {% for product in products %}
    <!-- <div class="col-lg-4 col-12 mb-2 px-sm-2">
      <div class="card t-store__card__imgwrapper  t-store__card__imgwrapper_1-1">
        <img src="{% thumbnail product.image 0x200 %}" alt="No Image" class="img-aspect p-2" />
        <div class="card-body">
          <h3 class="card-subtitle font-weight-light">
            <a href="{% url 'store:product_details' product.slug %}">{{product.name}}</a>
          </h3>
          <h4 class="card-text">
            <span class="badge badge-warning">Rs.{{product.price}}</span>
          </h4> -->



      <div class="col d-flex justify-content-center">
        <div class="col-sm-6">
            <div class="t-store__card__imgwrapper  t-store__card__imgwrapper_1-1" style="width: 18rem;"
              style="border:none">
              <img class="js-product-img t-store__card__bgimg t-bgimg loaded" src="{% thumbnail product.image 0x200 %}"
                alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'store:product_details' product.slug %}">{{product.name}}</a></h5>
                <h5 class="card-title">UZS {{product.price}}</h5>
                <p class="card-text">{{product.description|truncatewords:23 }}</p>
              </div>
            </div>
        </div>
      </div>    


    {% empty %}
    
    <div class="col-12 text-center">
      <h3 class="font-weight-light my-4 py-4" style="color:#6D0069">Tovar aniqlanmadi</h3>
    </div>
    {% endfor %}
  </div>
{% if products|length != 0 %}
  <nav style="text-align:center">
    {% with page_obj as page %}
    <div class="mt-2">
      <p class="my-2">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
      </p>
      <center>
      <ul class="pagination d-flex justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
          <a href="?page={{ page.previous_page_number }}" class="page-link" style="color:#6D0069">
            Ortga
          </a>
        </li>
        {% endif %}
        <li class="page-item active text-center" style="text-align:center">
          <a class="page-link" style="background:#6D0069; color:white; border-color:white">{{ page.number }}</a>
        </li>
        {% if page.has_next %}
        <li class="page-item text-center">
          <a href="?page={{ page.next_page_number }}" class="page-link "  style="background:#6D0069; color:white" >
            Keyingisi
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% endwith %}
  </nav>
  {% endif %}
  </center>
</div>
</div>  
<script> 
   document.querySelector("#div_id_price > div").className = "d-flex justify-space-between align-items-center";
  document.querySelectorAll("#div_id_price input").forEach((i) => {
    i.classList.add("form-control")
    i.style.minWidth = '10px'
  });
  document.querySelectorAll(".filter-form .form-control").forEach((i) => i.classList.add("form-control-sm"));
</script> 

{% endblock content %}

store/templates/store/similar.html
{% load thumbnail %}
<h3 class="font-weight-light mb-0" style="color:#6D0069">O'xshash Tovarlar</h3>
<hr />
<div class="row my-2">
  {% for product in products %}
  <div class="col-lg-3 col-md-4 col-12">
    <div class="card shadow-sm h-100">
      <img
        src="{% thumbnail product.image 0x150 %}"
        alt="{{product.name}}"
        class="card-img-top img-aspect p-2"
      />
      <div class="card-body">
        <h4 class="card-subtitle font-weight-light mb-1">
          <a href="{{ product.get_absolute_url }}">{{product.name}}</a>
        </h4>
        <h5 class="mb-0">
          <span class="badge badge-warning" style="color:#6D0069">UZS{{product.price}}</span>
        </h5>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="col-12">
    <h5 class="font-weight-light" style="color:#6D0069">O'xshash tovarlar topilmadi.</h5>
  </div>
  {% endfor %}
</div>

store/templates/store/slider.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--Carousel Wrapper-->
<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel" style="border:none">

  <!--Indicators-->
  <div class="carousel-inner" role="listbox" style="border:none">
    {% for p in products_picked %}
    <!--First slide-->
    {% if forloop.counter0|divisibleby:4 %}
    <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" style="border:none"> {% endif %}

      <div class="col-md-3" style="float:left" style="border:none">
       <div class="card mb-4" style="width:300px; height:300px; justify-content:center; display:flex; border:none">
          <img class="w3-round"
            src="{{p.image.url}}" alt="Cardimg">
        </div>
      </div>
      {% if forloop.counter|divisibleby:4 or forloop.last %}
    </div>{% endif %}
    {% endfor%}
    <!--/.First slide-->
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>